from __future__ import annotations

from typing import List, Tuple
from src.models.validation_report import ValidationReport
from src.models.optimization_report import (
    OptimizationRecommendation,
    RecommendationEvidence,
    StrategyOptimization,
)


class StrategyAnalyzer:
    """
    Analyzes specific execution behaviors per trading strategy to recommend
    active adjustments (e.g. suspension, risk dampening, or weight enhancement).
    """

    def analyze(self, report: ValidationReport) -> Tuple[List[OptimizationRecommendation], List[StrategyOptimization]]:
        recommendations = []
        strategy_recs = []

        strategies = report.strategy_performances
        if not strategies:
            return recommendations, strategy_recs

        for s in strategies:
            strat_upper = s.strategy_name.upper()

            # 1. Reduce exposure on expiry days for expiry strategies
            if "EXPIRY" in strat_upper or "SCALPING" in strat_upper:
                # Expiry strategies or high-frequency/scalping strategies often suffer from high decay or noise
                # Suggest restricting exposure on expiry days or high-volatility environments
                evidence = RecommendationEvidence(
                    historical_sample_size=s.total_candidates,
                    observed_improvement_potential=15.0,
                    affected_strategies=[s.strategy_name],
                    expected_trade_off="Protects against catastrophic tail loss on expiry days while reducing transaction friction.",
                    confidence_score=92.0,
                )
                rec = OptimizationRecommendation(
                    recommendation_id=f"REC_EXPIRY_RISK_{strat_upper}",
                    category="RISK_EXPOSURE",
                    title=f"Dampen Expiry-Day Exposure for {s.strategy_name}",
                    description="Reduce max contracts/lots and increase slippage buffers on option contracts close to expiry.",
                    current_value="Standard position sizing applies on expiry day",
                    recommended_value="Implement a 50% position sizing haircut for contracts expiring within 24 hours.",
                    evidence=evidence,
                    rationale=(
                        f"Strategy {s.strategy_name} is highly active on or near contract expiry. "
                        "Gamma risk spikes exponentially in the final hours of trading. Restricting exposure "
                        "prevents sudden slippage and adverse option price swings."
                    ),
                )
                recommendations.append(rec)

                strategy_recs.append(
                    StrategyOptimization(
                        strategy_name=s.strategy_name,
                        current_accuracy=s.avg_confidence_score,
                        recommended_action="REDUCE_WEIGHT_ON_EXPIRY",
                        rationale="Restrict position sizing by 50% during the final 24 hours before expiration to control Gamma risk.",
                    )
                )

            # 2. Suspend or enhance a strategy with very poor average confidence (< 45)
            elif s.avg_confidence_score < 45.0:
                evidence = RecommendationEvidence(
                    historical_sample_size=s.total_candidates,
                    observed_improvement_potential=25.0,
                    affected_strategies=[s.strategy_name],
                    expected_trade_off="Removes capital drag from underperforming strategy, but temporarily limits variety.",
                    confidence_score=95.0,
                )
                rec = OptimizationRecommendation(
                    recommendation_id=f"REC_SUSPEND_{strat_upper}",
                    category="STRATEGY_WEIGHTS",
                    title=f"Temporarily Suspend Strategy: {s.strategy_name}",
                    description="De-allocate all portfolio risk from this strategy until regime suitability improves.",
                    current_value=f"Average Confidence: {s.avg_confidence_score:.2f}",
                    recommended_value="Suspend execution of signals generated by this strategy (weight = 0.0).",
                    evidence=evidence,
                    rationale=(
                        f"The {s.strategy_name} strategy has a very low average confidence score of {s.avg_confidence_score:.2f}. "
                        "Executing its signals acts as a persistent drag on capital and overall portfolio efficiency."
                    ),
                )
                recommendations.append(rec)

                strategy_recs.append(
                    StrategyOptimization(
                        strategy_name=s.strategy_name,
                        current_accuracy=s.avg_confidence_score,
                        recommended_action="SUSPEND",
                        rationale="Average conviction score is critically low. Suspend live allocation until re-calibration is complete.",
                    )
                )

            # 3. High performing strategy (avg_confidence_score >= 70.0) -> Recommend weight boost
            elif s.avg_confidence_score >= 70.0:
                evidence = RecommendationEvidence(
                    historical_sample_size=s.total_candidates,
                    observed_improvement_potential=12.0,
                    affected_strategies=[s.strategy_name],
                    expected_trade_off="Increases capital commitment to high-performing style, which may increase drawdowns if regime shifts.",
                    confidence_score=85.0,
                )
                rec = OptimizationRecommendation(
                    recommendation_id=f"REC_BOOST_{strat_upper}",
                    category="STRATEGY_WEIGHTS",
                    title=f"Enhance Exposure for High-Conviction Strategy: {s.strategy_name}",
                    description="Increase baseline suitability and size multiplier for this high-performing strategy.",
                    current_value=f"Average Confidence: {s.avg_confidence_score:.2f}",
                    recommended_value="Increase strategy suitability multiplier by 0.20.",
                    evidence=evidence,
                    rationale=(
                        f"Strategy {s.strategy_name} exhibits excellent conviction scores (Avg: {s.avg_confidence_score:.2f}). "
                        "Capitalizing on established edge by scaling up allocation enhances absolute yields."
                    ),
                )
                recommendations.append(rec)

                strategy_recs.append(
                    StrategyOptimization(
                        strategy_name=s.strategy_name,
                        current_accuracy=s.avg_confidence_score,
                        recommended_action="INCREASE_WEIGHT",
                        rationale="Strategy shows exceptionally high conviction. Scale up baseline suitability weight to capture maximum alpha.",
                    )
                )

        return recommendations, strategy_recs
