// src/frontend/services/order_lifecycle.ts
import {
  OrderLifecycleReport,
  OrderLifecycleEvent,
  OrderLifecycleStatistics,
} from "../types";

let mockReports: OrderLifecycleReport[] = [
  {
    order_id: "ORD-LC-101",
    tradingsymbol: "NIFTY26JUL2424200CE",
    exchange: "NFO",
    transaction_type: "BUY",
    quantity: 1000,
    product: "NRML",
    order_type: "LIMIT",
    current_state: "PARTIALLY_FILLED",
    progress: {
      requested_quantity: 1000,
      filled_quantity: 400,
      remaining_quantity: 600,
      average_fill_price: 152.40,
      weighted_average: 152.40,
      completion_percentage: 40.0,
    },
    timeline: {
      order_id: "ORD-LC-101",
      tradingsymbol: "NIFTY26JUL2424200CE",
      events: [
        {
          event_id: "E1",
          timestamp: "2026-07-11 09:15:00",
          previous_state: "NONE",
          new_state: "CREATED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
          broker_response: "Order initialized in database",
          reason: "Manual entry generated by operator",
        },
        {
          event_id: "E2",
          timestamp: "2026-07-11 09:15:02",
          previous_state: "CREATED",
          new_state: "VALIDATED",
          trigger_source: "SYSTEM",
          operator: "SYSTEM",
          broker_response: "Pre-flight checks valid",
          reason: "Quantity, margin, and collateral constraints passed",
        },
        {
          event_id: "E3",
          timestamp: "2026-07-11 09:15:05",
          previous_state: "VALIDATED",
          new_state: "PENDING_CONFIRMATION",
          trigger_source: "SYSTEM",
          operator: "SYSTEM",
          broker_response: "Operator authentication pending",
          reason: "Execution confirmation popup activated",
        },
        {
          event_id: "E4",
          timestamp: "2026-07-11 09:15:08",
          previous_state: "PENDING_CONFIRMATION",
          new_state: "CONFIRMED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
          broker_response: "Operator bypass approved",
          reason: "Confirmed manually via workspace authorization card",
        },
        {
          event_id: "E5",
          timestamp: "2026-07-11 09:15:10",
          previous_state: "CONFIRMED",
          new_state: "SUBMITTED",
          trigger_source: "SYSTEM",
          operator: "SYSTEM",
          broker_response: "Sent to Kite BrokerGateway",
          reason: "Order successfully transmitted to Zerodha API",
        },
        {
          event_id: "E6",
          timestamp: "2026-07-11 09:15:12",
          previous_state: "SUBMITTED",
          new_state: "OPEN",
          trigger_source: "BROKER",
          operator: "SYSTEM",
          broker_response: "Exchange status: OPEN",
          reason: "Order accepted by NSE/NFO matching engine",
        },
        {
          event_id: "E7",
          timestamp: "2026-07-11 09:15:20",
          previous_state: "OPEN",
          new_state: "PARTIALLY_FILLED",
          trigger_source: "BROKER",
          operator: "SYSTEM",
          broker_response: "Fill: 400 @ 152.40",
          reason: "Matching engine executed first tranche",
        },
      ],
    },
    modification_history: [
      {
        modification_id: "M1",
        timestamp: "2026-07-11 09:15:15",
        previous_quantity: 1000,
        previous_price: 150.00,
        new_quantity: 1000,
        new_price: 152.50,
        status: "SUCCESS",
      },
    ],
    broker_remarks: "Partially executed on exchange book",
    timestamp: "2026-07-11 09:15:20",
  },
  {
    order_id: "ORD-LC-102",
    tradingsymbol: "BANKNIFTY26JUL2451000PE",
    exchange: "NFO",
    transaction_type: "SELL",
    quantity: 300,
    product: "MIS",
    order_type: "LIMIT",
    current_state: "FILLED",
    progress: {
      requested_quantity: 300,
      filled_quantity: 300,
      remaining_quantity: 0,
      average_fill_price: 345.10,
      weighted_average: 345.10,
      completion_percentage: 100.0,
    },
    timeline: {
      order_id: "ORD-LC-102",
      tradingsymbol: "BANKNIFTY26JUL2451000PE",
      events: [
        {
          event_id: "E102-1",
          timestamp: "2026-07-11 09:20:00",
          previous_state: "NONE",
          new_state: "CREATED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
        },
        {
          event_id: "E102-2",
          timestamp: "2026-07-11 09:20:05",
          previous_state: "CREATED",
          new_state: "CONFIRMED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
        },
        {
          event_id: "E102-3",
          timestamp: "2026-07-11 09:20:07",
          previous_state: "CONFIRMED",
          new_state: "SUBMITTED",
          trigger_source: "SYSTEM",
          operator: "SYSTEM",
        },
        {
          event_id: "E102-4",
          timestamp: "2026-07-11 09:20:10",
          previous_state: "SUBMITTED",
          new_state: "FILLED",
          trigger_source: "BROKER",
          operator: "SYSTEM",
          broker_response: "Fully executed: 300 @ 345.10",
        },
      ],
    },
    modification_history: [],
    broker_remarks: "Fully executed",
    timestamp: "2026-07-11 09:20:10",
  },
  {
    order_id: "ORD-LC-103",
    tradingsymbol: "FINNIFTY26JUL2421200CE",
    exchange: "NFO",
    transaction_type: "BUY",
    quantity: 800,
    product: "NRML",
    order_type: "LIMIT",
    current_state: "CANCELLED",
    progress: {
      requested_quantity: 800,
      filled_quantity: 0,
      remaining_quantity: 800,
      average_fill_price: 0.0,
      weighted_average: 0.0,
      completion_percentage: 0.0,
    },
    timeline: {
      order_id: "ORD-LC-103",
      tradingsymbol: "FINNIFTY26JUL2421200CE",
      events: [
        {
          event_id: "E103-1",
          timestamp: "2026-07-11 09:30:00",
          previous_state: "NONE",
          new_state: "CREATED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
        },
        {
          event_id: "E103-2",
          timestamp: "2026-07-11 09:30:12",
          previous_state: "CREATED",
          new_state: "CANCELLED",
          trigger_source: "OPERATOR",
          operator: "pvpk06@gmail.com",
          reason: "User closed workspace request",
        },
      ],
    },
    modification_history: [],
    cancellation_record: {
      cancellation_id: "C_103",
      timestamp: "2026-07-11 09:30:12",
      requested_by: "pvpk06@gmail.com",
      reason: "User cancelled manually",
      status: "SUCCESS",
    },
    broker_remarks: "Cancelled by user",
    timestamp: "2026-07-11 09:30:12",
  },
];

export function getOrderLifecycleReports(): OrderLifecycleReport[] {
  return [...mockReports];
}

export function getOrderLifecycleStatistics(): OrderLifecycleStatistics {
  const completed = mockReports.filter(r => r.current_state === "FILLED");
  const total = mockReports.length;

  return {
    average_fill_time: 14.5, // seconds
    broker_latency: 18.2, // ms
    exchange_latency: 26.4, // ms
    fill_efficiency: 80.0, // %
    slippage: 0.35, // INR
    partial_fill_percentage: 33.3,
    modification_count: 1,
    cancellation_rate: 33.3,
    execution_success_rate: 66.7,
  };
}

export function createOrderLifecycle(
  symbol: string,
  side: "BUY" | "SELL",
  quantity: number,
  price: number
): OrderLifecycleReport {
  const orderId = "ORD-LC-" + Math.floor(Math.random() * 9000 + 1000);
  const nowStr = new Date().toISOString().replace("T", " ").substring(0, 19);

  const initialEvent: OrderLifecycleEvent = {
    event_id: "E-" + orderId + "-1",
    timestamp: nowStr,
    previous_state: "NONE",
    new_state: "CREATED",
    trigger_source: "OPERATOR",
    operator: "pvpk06@gmail.com",
    broker_response: "Order registered on client terminal",
    reason: "Awaiting confirmation authorization",
  };

  const newReport: OrderLifecycleReport = {
    order_id: orderId,
    tradingsymbol: symbol,
    exchange: "NFO",
    transaction_type: side,
    quantity,
    product: "NRML",
    order_type: "LIMIT",
    current_state: "CREATED",
    progress: {
      requested_quantity: quantity,
      filled_quantity: 0,
      remaining_quantity: quantity,
      average_fill_price: 0.0,
      weighted_average: 0.0,
      completion_percentage: 0.0,
    },
    timeline: {
      order_id: orderId,
      tradingsymbol: symbol,
      events: [initialEvent],
    },
    modification_history: [],
    broker_remarks: "Awaiting operator authorization",
    timestamp: nowStr,
  };

  mockReports.unshift(newReport);
  return newReport;
}

export function transitionOrder(
  orderId: string,
  newState: string,
  remarks = "State transition synchronized"
): OrderLifecycleReport {
  const order = mockReports.find(r => r.order_id === orderId);
  if (!order) throw new Error("Order not found");

  const nowStr = new Date().toISOString().replace("T", " ").substring(0, 19);
  const prev = order.current_state;

  const event: OrderLifecycleEvent = {
    event_id: "E-" + orderId + "-" + (order.timeline.events.length + 1),
    timestamp: nowStr,
    previous_state: prev,
    new_state: newState,
    trigger_source: "BROKER",
    operator: "SYSTEM",
    broker_response: remarks,
  };

  order.current_state = newState;
  order.timeline.events.push(event);
  order.broker_remarks = remarks;
  order.timestamp = nowStr;

  if (newState === "FILLED") {
    order.progress.filled_quantity = order.quantity;
    order.progress.remaining_quantity = 0;
    order.progress.completion_percentage = 100.0;
  }

  return { ...order };
}

export function modifyOrder(
  orderId: string,
  newQuantity: number,
  newPrice: number
): OrderLifecycleReport {
  const order = mockReports.find(r => r.order_id === orderId);
  if (!order) throw new Error("Order not found");

  const nowStr = new Date().toISOString().replace("T", " ").substring(0, 19);

  order.modification_history.push({
    modification_id: "M-" + orderId + "-" + (order.modification_history.length + 1),
    timestamp: nowStr,
    previous_quantity: order.quantity,
    previous_price: order.progress.average_fill_price || 150.0,
    new_quantity: newQuantity,
    new_price: newPrice,
    status: "SUCCESS",
  });

  order.quantity = newQuantity;
  order.progress.requested_quantity = newQuantity;
  order.progress.remaining_quantity = Math.max(0, newQuantity - order.progress.filled_quantity);
  order.progress.completion_percentage = (order.progress.filled_quantity / newQuantity) * 100;
  order.broker_remarks = `Modified parameters: Qty -> ${newQuantity}, Px -> ${newPrice}`;

  const event: OrderLifecycleEvent = {
    event_id: "E-" + orderId + "-" + (order.timeline.events.length + 1),
    timestamp: nowStr,
    previous_state: order.current_state,
    new_state: "MODIFIED",
    trigger_source: "OPERATOR",
    operator: "pvpk06@gmail.com",
    broker_response: `Parameters updated to Qty: ${newQuantity}, Price: ${newPrice}`,
  };
  order.timeline.events.push(event);

  return { ...order };
}

export function cancelOrder(
  orderId: string,
  reason: string
): OrderLifecycleReport {
  const order = mockReports.find(r => r.order_id === orderId);
  if (!order) throw new Error("Order not found");

  const nowStr = new Date().toISOString().replace("T", " ").substring(0, 19);

  order.cancellation_record = {
    cancellation_id: "C-" + orderId,
    timestamp: nowStr,
    requested_by: "pvpk06@gmail.com",
    reason,
    status: "SUCCESS",
  };

  order.current_state = "CANCELLED";
  order.broker_remarks = `Cancelled: ${reason}`;

  const event: OrderLifecycleEvent = {
    event_id: "E-" + orderId + "-" + (order.timeline.events.length + 1),
    timestamp: nowStr,
    previous_state: order.current_state,
    new_state: "CANCELLED",
    trigger_source: "OPERATOR",
    operator: "pvpk06@gmail.com",
    broker_response: `Cancellation authorized by operator: ${reason}`,
  };
  order.timeline.events.push(event);

  return { ...order };
}
